export type Trip = {
  slug: string
  title: string
  titlePl: string
  titleDe: string
  titleIt: string
  titleAr: string
  description: string
  descriptionPl: string
  descriptionDe: string
  descriptionIt: string
  descriptionAr: string
  price: string
  category: "Sea" | "Desert" | "Culture" | "Service"
  image: string
}

export const trips: Trip[] = [
  {
    slug: "airport-transfers",
    title: "Airport Transfers",
    titlePl: "Transfer z Lotniska",
    titleDe: "Flughafentransfers",
    titleIt: "Trasferimenti Aeroportuali",
    titleAr: "خدمة النقل من المطار",
    description: "Comfortable private transfers between Marsa Alam Airport and your hotel, on time, every time.",
    descriptionPl: "Wygodny prywatny transfer między lotniskiem Marsa Alam a Twoim hotelem, zawsze na czas.",
    descriptionDe: "Komfortable private Transfers zwischen dem Flughafen Marsa Alam und Ihrem Hotel, immer pünktlich.",
    descriptionIt: "Trasferimenti privati ​​comodi tra l'aeroporto di Marsa Alam e il tuo hotel, sempre puntuali.",
    descriptionAr: "نقل خاص مريح بين مطار مرسى علم وفندقك، في الموعد المحدد، في كل مرة.",
    price: "From €20",
    category: "Service",
    image: "/images/trip-transfer.png",
  },
  {
    slug: "abu-dabbab",
    title: "Abu Dabbab",
    titlePl: "Abu Dabbab",
    titleDe: "Abu Dabbab",
    titleIt: "Abu Dabbab",
    titleAr: "أبو دباب",
    description: "Swim with dugongs and sea turtles in one of the Red Sea's most beautiful sheltered bays.",
    descriptionPl: "Pływaj z dugongami i żółwiami morskimi w jednej z najpiękniejszych osłoniętych zatok Morza Czerwonego.",
    descriptionDe: "Schwimmen Sie mit Dugongs und Meeresschildkröten in einer der schönsten geschützten Buchten des Roten Meeres.",
    descriptionIt: "Nuota con i dugonghi e le tartarughe marine in una delle baie riparate più belle del Mar Rosso.",
    descriptionAr: "اسبح مع أبقار البحر والسلاحف البحرية في واحدة من أجمل الخلجان المحمية في البحر الأحمر.",
    price: "From €35",
    category: "Sea",
    image: "/images/trip-abu-dabbab.png",
  },
  {
    slug: "marsa-mubarak",
    title: "Marsa Mubarak",
    titlePl: "Marsa Mubarak",
    titleDe: "Marsa Mubarak",
    titleIt: "Marsa Mubarak",
    titleAr: "مرسى مبارك",
    description: "Snorkel over seagrass meadows and vibrant coral home to turtles and colorful reef fish.",
    descriptionPl: "Nurkuj nad łąkami traw morskich i żywymi koralowcami, domem żółwi i kolorowych ryb rafowych.",
    descriptionDe: "Schnorcheln Sie über Seegraswiesen und lebendigen Korallen, die Heimat von Schildkröten und bunten Rifffischen sind.",
    descriptionIt: "Fai snorkeling sui prati di alghe marine e coralli vivaci, casa di tartarughe e pesci di barriera colorati.",
    descriptionAr: "اغطس فوق مروج الأعشاب البحرية والشعاب المرجانية النابضة بالحياة موطن السلاحف والأسماك الملونة.",
    price: "€50 (Snorkeling) • €95 (Diving) • €95 (Intro Dive)",
    category: "Sea",
    image: "/images/trip-marsa-mubarak.png",
  },
  {
    slug: "coral-garden",
    title: "Coral Garden",
    titlePl: "Ogród Koralowy",
    titleDe: "Korallengarten",
    titleIt: "Giardino di Corallo",
    titleAr: "حديقة المرجان",
    description: "Explore stunning coral formations teeming with colorful marine life in crystal-clear waters.",
    descriptionPl: "Odkryj wspaniałe formacje koralowe pełne kolorowego życia morskiego w krystalicznie czystych wodach.",
    descriptionDe: "Erkunden Sie atemberaubende Korallenformationen voller buntem Meeresleben in kristallklarem Wasser.",
    descriptionIt: "Esplora splendide formazioni coralline piene di vita marina colorata in acque cristalline.",
    descriptionAr: "استكشف تشكيلات مرجانية مذهلة تعج بالحياة البحرية الملونة في مياه صافية.",
    price: "€50 (Snorkeling) • €70 (Diving) • €95 (Intro Dive)",
    category: "Sea",
    image: "/images/trip-marsa-mubarak.png",
  },
  {
    slug: "samadi-dolphin",
    title: "Samadi Dolphin",
    titlePl: "Samadi Dolphin",
    titleDe: "Samadi Delfin",
    titleIt: "Samadi Delfini",
    titleAr: "سمادي دولفين",
    description: "Swim with wild dolphins in their natural habitat - an unforgettable Red Sea experience.",
    descriptionPl: "Pływaj z dzikimi delfinami w ich naturalnym środowisku - niezapomniane doświadczenie na Morzu Czerwonym.",
    descriptionDe: "Schwimmen Sie mit wilden Delfinen in ihrem natürlichen Lebensraum - ein unvergessliches Erlebnis im Roten Meer.",
    descriptionIt: "Nuota con i delfini selvatici nel loro habitat naturale - un'esperienza indimenticabile nel Mar Rosso.",
    descriptionAr: "اسبح مع الدلافين البرية في موطنها الطبيعي - تجربة لا تُنسى في البحر الأحمر.",
    price: "€58 (Snorkeling) • €105 (Diving) • €80 (Intro Dive)",
    category: "Sea",
    image: "/images/trip-hamata.png",
  },
  {
    slug: "sharm-el-luli",
    title: "Sharm El Luli",
    titlePl: "Sharm El Luli",
    titleDe: "Sharm El Luli",
    titleIt: "Sharm El Luli",
    titleAr: "شرم اللولي",
    description: "Relax on powder-white sand beside the clearest turquoise lagoon on the coast.",
    descriptionPl: "Zrelaksuj się na białym jak puder piasku obok najczystszej turkusowej laguny na wybrzeżu.",
    descriptionDe: "Entspannen Sie am puderfein weißen Sand neben der klarsten türkisfarbenen Lagune an der Küste.",
    descriptionIt: "Rilassati sulla sabbia bianca come la polvere accanto alla laguna turchese più limpida della costa.",
    descriptionAr: "استرخ على الرمال البيضاء الناعمة بجوار البحيرة الفيروزية الأكثر صفاءً على الساحل.",
    price: "€40 (Half Day) • €55 (Full Day)",
    category: "Sea",
    image: "/images/trip-sharm-el-luli.png",
  },
  {
    slug: "hamata-islands",
    title: "Hamata Islands",
    titlePl: "Wyspy Hamata",
    titleDe: "Hamata-Inseln",
    titleIt: "Isole Hamata",
    titleAr: "جزر حماطة",
    description: "A full-day boat trip to pristine islands, mangroves and untouched snorkeling spots.",
    descriptionPl: "Całodniowa wycieczka łodzią do dziewiczych wysp, namorzyn i nienaruszonych miejsc do nurkowania.",
    descriptionDe: "Ein ganztägiger Bootsausflug zu unberührten Inseln, Mangroven und unberührten Schnorchelplätzen.",
    descriptionIt: "Un'escursione in barca di un'intera giornata verso isole incontaminate, mangrovie e siti di snorkeling incontaminati.",
    descriptionAr: "رحلة بالقارب ليوم كامل إلى جزر نقية وأشجار المانغروف وأماكن غطس بكر.",
    price: "€60",
    category: "Sea",
    image: "/images/trip-hamata.png",
  },
  {
    slug: "sataya-day",
    title: "Sataya (Day Trip)",
    titlePl: "Sataya (Jednodniowa)",
    titleDe: "Sataya (Tagesausflug)",
    titleIt: "Sataya (Gita giornaliera)",
    titleAr: "ستايا (رحلة يوم)",
    description: "Visit the famous Dolphin Reef for an incredible day of swimming with spinner dolphins.",
    descriptionPl: "Odwiedź słynną Rafę Delfinów na niesamowity dzień pływania z delfinami wirującymi.",
    descriptionDe: "Besuchen Sie das berühmte Delphinriff für einen unglaublichen Tag mit Spinnerdelfinen.",
    descriptionIt: "Visita la famosa barriera dei delfini per un'incredibile giornata di nuoto con i delfini rotatori.",
    descriptionAr: "قم بزيارة الشعاب المرجانية الشهيرة للدلافين ليوم لا يُصدق من السباحة مع الدلافين الدوارة.",
    price: "€105",
    category: "Sea",
    image: "/images/trip-hamata.png",
  },
  {
    slug: "sataya-overnight",
    title: "Sataya (Overnight)",
    titlePl: "Sataya (Z Noclegiem)",
    titleDe: "Sataya (Übernachtung)",
    titleIt: "Sataya (Pernottamento)",
    titleAr: "ستايا (رحلة مبيت)",
    description: "Two-day liveaboard adventure to Sataya Reef with dolphins, pristine reefs, and starlit nights.",
    descriptionPl: "Dwudniowa przygoda na pokładzie statku do Rafy Sataya z delfinami, dziewiczymi rafami i gwiaździstymi nocami.",
    descriptionDe: "Zweitägiges Liveaboard-Abenteuer zum Sataya-Riff mit Delfinen, unberührten Riffen und sternenklaren Nächten.",
    descriptionIt: "Avventura di due giorni in barca a Sataya Reef con delfini, barriere incontaminate e notti stellate.",
    descriptionAr: "مغامرة مبيت لمدة يومين إلى شعاب ستايا مع الدلافين والشعاب البكر والليالي المرصعة بالنجوم.",
    price: "€180 (Snorkeling) • €260 (Diving) • €210 (Intro Dive)",
    category: "Sea",
    image: "/images/trip-hamata.png",
  },
  {
    slug: "sea-scope",
    title: "Sea Scope",
    titlePl: "Sea Scope",
    titleDe: "Sea Scope",
    titleIt: "Sea Scope",
    titleAr: "سي سكوب",
    description: "Discover the underwater world in comfort aboard a semi-submarine — no swimming required.",
    descriptionPl: "Odkryj podwodny świat w komforcie na pokładzie półłodzi podwodnej — pływanie nie jest wymagane.",
    descriptionDe: "Entdecken Sie die Unterwasserwelt bequem an Bord eines Halb-U-Boots — Schwimmen nicht erforderlich.",
    descriptionIt: "Scopri il mondo sottomarino comodamente a bordo di un semi-sottomarino — non è richiesto nuotare.",
    descriptionAr: "اكتشف العالم تحت الماء بشكل مريح على متن غواصة نصفية - لا حاجة للسباحة.",
    price: "From $28",
    category: "Sea",
    image: "/images/trip-sea-scope.png",
  },
  {
    slug: "nefertari-yacht",
    title: "Nefertari Yacht",
    titlePl: "Jacht Nefertari",
    titleDe: "Nefertari-Yacht",
    titleIt: "Yacht Nefertari",
    titleAr: "يخت نفرتاري",
    description: "A private luxury yacht cruise with snorkeling stops, lunch and endless sea views.",
    descriptionPl: "Prywatny luksusowy rejs jachtem z przystankami do nurkowania, lunchem i niekończącymi się widokami na morze.",
    descriptionDe: "Eine private Luxusyachtkreuzfahrt mit Schnorchel-Stopps, Mittagessen und endlosem Meerblick.",
    descriptionIt: "Una crociera privata su yacht di lusso con soste per snorkeling, pranzo e viste infinite sul mare.",
    descriptionAr: "رحلة بحرية خاصة فاخرة على متن يخت مع محطات للغطس والغداء وإطلالات بحرية لا نهاية لها.",
    price: "From $75",
    category: "Sea",
    image: "/images/trip-yacht.png",
  },
  {
    slug: "rosetta",
    title: "Rosetta",
    titlePl: "Rosetta",
    titleDe: "Rosetta",
    titleIt: "Rosetta",
    titleAr: "روزيتا",
    description: "A relaxed day cruise with sun decks, swimming and reef snorkeling for the whole family.",
    descriptionPl: "Relaksujący rejs dzienny z tarasami słonecznymi, pływaniem i nurkowaniem na rafie dla całej rodziny.",
    descriptionDe: "Eine entspannte Tageskreuzfahrt mit Sonnendecks, Schwimmen und Riffschnorcheln für die ganze Familie.",
    descriptionIt: "Una crociera giornaliera rilassante con ponti prendisole, nuoto e snorkeling sulla barriera per tutta la famiglia.",
    descriptionAr: "رحلة بحرية يومية مريحة مع أسطح تشمس وسباحة وغطس على الشعاب المرجانية لجميع أفراد الأسرة.",
    price: "From $50",
    category: "Sea",
    image: "/images/trip-rosetta.png",
  },
  {
    slug: "wadi-el-gemal",
    title: "Wadi El Gemal",
    titlePl: "Wadi El Gemal",
    titleDe: "Wadi El Gemal",
    titleIt: "Wadi El Gemal",
    titleAr: "وادي الجمال",
    description: "Explore a protected national park of desert valleys, wildlife and ancient landscapes.",
    descriptionPl: "Odkryj chroniony park narodowy z pustynnych dolin, dzikiej przyrody i starożytnych krajobrazów.",
    descriptionDe: "Erkunden Sie einen geschützten Nationalpark mit Wüstentälern, Wildtieren und alten Landschaften.",
    descriptionIt: "Esplora un parco nazionale protetto di valli desertiche, fauna selvatica e paesaggi antichi.",
    descriptionAr: "استكشف حديقة وطنية محمية من الوديان الصحراوية والحياة البرية والمناظر الطبيعية القديمة.",
    price: "From $45",
    category: "Desert",
    image: "/images/trip-wadi-el-gemal.png",
  },
  {
    slug: "super-safari",
    title: "Super Safari",
    titlePl: "Super Safari",
    titleDe: "Super Safari",
    titleIt: "Super Safari",
    titleAr: "سفاري خارق",
    description: "Jeep adventure across the dunes with a Bedouin dinner, camel ride and sunset views.",
    descriptionPl: "Przygoda jeepem przez wydmy z kolacją beduińską, przejażdżką na wielbłądach i widokami zachodu słońca.",
    descriptionDe: "Jeep-Abenteuer durch die Dünen mit Beduinen-Abendessen, Kamelritt und Sonnenuntergang.",
    descriptionIt: "Avventura in jeep tra le dune con cena beduina, giro in cammello e viste al tramonto.",
    descriptionAr: "مغامرة بالجيب عبر الكثبان مع عشاء بدوي وركوب الجمال ومشاهدة غروب الشمس.",
    price: "From $38",
    category: "Desert",
    image: "/images/trip-safari.png",
  },
  {
    slug: "luxor",
    title: "Luxor (Day / Overnight)",
    titlePl: "Luxor (Dzień / Nocleg)",
    titleDe: "Luxor (Tag / Übernachtung)",
    titleIt: "Luxor (Giorno / Pernottamento)",
    titleAr: "الأقصر (يوم / مبيت)",
    description: "Visit Karnak, the Valley of the Kings and the temples of the world's greatest open-air museum.",
    descriptionPl: "Odwiedź Karnak, Dolinę Królów i świątynie największego muzeum na świeżym powietrzu na świecie.",
    descriptionDe: "Besuchen Sie Karnak, das Tal der Könige und die Tempel des größten Freilichtmuseums der Welt.",
    descriptionIt: "Visita Karnak, la Valle dei Re e i templi del più grande museo a cielo aperto del mondo.",
    descriptionAr: "قم بزيارة الكرنك ووادي الملوك ومعابد أعظم متحف في الهواء الطلق في العالم.",
    price: "From $85",
    category: "Culture",
    image: "/images/trip-luxor.png",
  },
  {
    slug: "aswan",
    title: "Aswan (Day / Overnight + Abu Simbel)",
    titlePl: "Asuan (Dzień / Nocleg + Abu Simbel)",
    titleDe: "Assuan (Tag / Übernachtung + Abu Simbel)",
    titleIt: "Assuan (Giorno / Pernottamento + Abu Simbel)",
    titleAr: "أسوان (يوم / مبيت + أبو سمبل)",
    description: "Discover the Nile, the High Dam and the magnificent temples of Abu Simbel.",
    descriptionPl: "Odkryj Nil, Wysoką Tamę i wspaniałe świątynie Abu Simbel.",
    descriptionDe: "Entdecken Sie den Nil, den Hochdamm und die prächtigen Tempel von Abu Simbel.",
    descriptionIt: "Scopri il Nilo, la Diga di Assuan e i magnifici templi di Abu Simbel.",
    descriptionAr: "اكتشف النيل والسد العالي ومعابد أبو سمبل الرائعة.",
    price: "From $180",
    category: "Culture",
    image: "/images/trip-aswan.png",
  },
  {
    slug: "cairo",
    title: "Cairo (Day / Overnight)",
    titlePl: "Kair (Dzień / Nocleg)",
    titleDe: "Kairo (Tag / Übernachtung)",
    titleIt: "Il Cairo (Giorno / Pernottamento)",
    titleAr: "القاهرة (يوم / مبيت)",
    description: "Stand before the Great Pyramids, the Sphinx and the treasures of the Egyptian Museum.",
    descriptionPl: "Stań przed Wielkimi Piramidami, Sfinksem i skarbami Muzeum Egipskiego.",
    descriptionDe: "Stehen Sie vor den Großen Pyramiden, der Sphinx und den Schätzen des Ägyptischen Museums.",
    descriptionIt: "Stai davanti alle Grandi Piramidi, alla Sfinge e ai tesori del Museo Egizio.",
    descriptionAr: "قف أمام الأهرامات العظيمة وأبو الهول وكنوز المتحف المصري.",
    price: "From $140",
    category: "Culture",
    image: "/images/trip-cairo.png",
  },
  {
    slug: "city-tours",
    title: "City Tours",
    titlePl: "Wycieczki Miejskie",
    titleDe: "Stadttouren",
    titleIt: "Tour della Città",
    titleAr: "جولات المدينة",
    description: "Explore local markets, coastal towns and hidden gems with a friendly local guide.",
    descriptionPl: "Odkryj lokalne targi, nadmorskie miasteczka i ukryte klejnoty z przyjaznym lokalnym przewodnikiem.",
    descriptionDe: "Erkunden Sie lokale Märkte, Küstenstädte und versteckte Schätze mit einem freundlichen lokalen Führer.",
    descriptionIt: "Esplora i mercati locali, le città costiere e i tesori nascosti con una guida locale amichevole.",
    descriptionAr: "استكشف الأسواق المحلية والمدن الساحلية والجواهر الخفية مع دليل محلي ودود.",
    price: "From $25",
    category: "Culture",
    image: "/images/trip-city-tours.png",
  },
  {
    slug: "diving-course",
    title: "Diving Course",
    titlePl: "Kurs Nurkowania",
    titleDe: "Tauchkurs",
    titleIt: "Corso di Immersione",
    titleAr: "دورة الغوص",
    description: "Learn to scuba dive with certified instructors on the Red Sea's spectacular reefs.",
    descriptionPl: "Naucz się nurkować z akwalungiem z certyfikowanymi instruktorami na spektakularnych rafach Morza Czerwonego.",
    descriptionDe: "Lernen Sie das Tauchen mit zertifizierten Lehrern an den spektakulären Riffen des Roten Meeres.",
    descriptionIt: "Impara a fare immersioni subacquee con istruttori certificati sulle spettacolari barriere del Mar Rosso.",
    descriptionAr: "تعلم الغوص مع مدربين معتمدين على الشعاب المرجانية الرائعة في البحر الأحمر.",
    price: "From €60 / $65 (Intro Dive) • €60 / $65 (Full Course)",
    category: "Sea",
    image: "/images/trip-diving.png",
  },
]

export const testimonials = [
  {
    name: "Emma Thompson",
    location: "United Kingdom",
    avatar: "/images/avatar-1.png",
    rating: 5,
    quote:
      "The Abu Dabbab trip was magical — we swam with a turtle within minutes! Everything was perfectly organized from pickup to lunch.",
  },
  {
    name: "Karim Nasser",
    location: "Egypt",
    avatar: "/images/avatar-2.png",
    rating: 5,
    quote:
      "The desert safari with Bedouin dinner under the stars was the highlight of our trip. The guides were warm and professional.",
  },
  {
    name: "Mei Lin",
    location: "Singapore",
    avatar: "/images/avatar-3.png",
    rating: 5,
    quote:
      "Booked the Luxor overnight tour and it exceeded every expectation. Marsa Tours truly delivers where desert meets the sea.",
  },
]
